# Generated by Django 5.0.2 on 2026-03-23 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=50)),
                ('uid', models.CharField(max_length=30)),
                ('edate', models.DateField()),
                ('etime', models.TimeField()),
                ('sevent', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'eventlog',
            },
        ),
    ]
