# Generated by Django 5.0.2 on 2026-03-23 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SalesReturnReport',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(blank=True, null=True)),
                ('invno', models.IntegerField(blank=True, null=True)),
                ('net', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('customername', models.CharField(blank=True, max_length=250, null=True)),
                ('userid', models.CharField(blank=True, max_length=13, null=True)),
                ('client_id', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'salesreturn_report',
                'managed': False,
            },
        ),
    ]
