# Generated by Django 4.2.7 on 2025-10-23 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SalesToday',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nettotal', models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True)),
                ('billno', models.IntegerField(blank=True, null=True)),
                ('type', models.CharField(blank=True, max_length=30, null=True)),
                ('userid', models.CharField(blank=True, max_length=10, null=True)),
                ('invdate', models.DateField(blank=True, null=True)),
                ('customername', models.CharField(blank=True, max_length=250, null=True)),
                ('client_id', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'sales_today',
                'managed': True,
                'indexes': [models.Index(fields=['client_id', 'invdate'], name='sales_today_client__b93795_idx'), models.Index(fields=['billno'], name='sales_today_billno_8aca06_idx')],
            },
        ),
        migrations.CreateModel(
            name='PurchaseToday',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('net', models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True)),
                ('billno', models.IntegerField(blank=True, null=True)),
                ('pbillno', models.IntegerField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('suppliername', models.CharField(blank=True, max_length=250, null=True)),
                ('client_id', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'purchase_today',
                'managed': True,
                'indexes': [models.Index(fields=['client_id', 'date'], name='purchase_to_client__629e60_idx'), models.Index(fields=['billno'], name='purchase_to_billno_cc9d51_idx')],
            },
        ),
    ]
