# Generated by Django 5.0.2 on 2026-03-23 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salestoday_purchasetoday', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salestoday',
            name='slno',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='SalesDaywise',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('total_bills', models.IntegerField(default=0)),
                ('total_amount', models.DecimalField(decimal_places=3, default=0, max_digits=15)),
                ('client_id', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'sales_daywise',
                'managed': True,
                'indexes': [models.Index(fields=['client_id', 'date'], name='sales_daywi_client__de87e8_idx')],
                'unique_together': {('date', 'client_id')},
            },
        ),
        migrations.CreateModel(
            name='SalesMonthwise',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('month_name', models.CharField(max_length=20)),
                ('month_number', models.IntegerField()),
                ('year', models.IntegerField()),
                ('total_bills', models.IntegerField(default=0)),
                ('total_amount', models.DecimalField(decimal_places=3, default=0, max_digits=15)),
                ('client_id', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'sales_monthwise',
                'managed': True,
                'indexes': [models.Index(fields=['client_id', 'year', 'month_number'], name='sales_month_client__4e6e11_idx')],
                'unique_together': {('month_number', 'year', 'client_id')},
            },
        ),
    ]
