# Generated by Django 5.0.2 on 2026-03-23 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RefreshTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=50)),
                ('edate', models.DateField()),
                ('etime', models.DateTimeField()),
                ('userid', models.CharField(max_length=20)),
                ('remark', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'refresh_tag',
            },
        ),
    ]
