# Generated by Django 5.0.2 on 2025-10-06 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllowedMenu',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=64)),
                ('client_id', models.CharField(max_length=64)),
                ('allowedMenuIds', models.CharField(max_length=500)),
                ('label', models.CharField(max_length=100, null=True)),
                ('path', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'user_menus',
            },
        ),
    ]
