# Generated by Django 5.0.2 on 2025-10-06 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accesscontroll', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allowedmenu',
            name='allowedMenuIds',
            field=models.JSONField(default=list),
        ),
    ]
