# Generated by Django 5.0.2 on 2026-03-23 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccSalesType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cd', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=100)),
                ('client_id', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'acc_sales_types',
            },
        ),
    ]
