# Generated by Django 5.0.2 on 2026-03-23 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(db_index=True, max_length=50)),
                ('code', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=200)),
                ('productcode', models.CharField(max_length=30)),
                ('barcode', models.CharField(blank=True, max_length=35, null=True)),
                ('bmrp', models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True)),
                ('salesprice', models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True)),
                ('quantity', models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True)),
            ],
            options={
                'db_table': 'stock_report',
            },
        ),
    ]
