# Generated by Django 5.0.2 on 2025-08-18 04:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app1', '0003_accinvmast_accledgers_accmaster_cashandbankaccmaster'),
    ]

    operations = [
        migrations.CreateModel(
            name='PunchIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('client_id', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.misel')),
            ],
            options={
                'db_table': 'punch_in',
            },
        ),
    ]
