# Generated by Django 5.0.2 on 2025-08-18 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PunchIn', '0001_initial'),
        ('app1', '0003_accinvmast_accledgers_accmaster_cashandbankaccmaster'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PunchIn',
            new_name='ShopLocation',
        ),
        migrations.AlterModelTable(
            name='shoplocation',
            table='shop_location',
        ),
    ]
