# Generated by Django 5.0.2 on 2025-08-28 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PunchIn', '0001_initial'),
        ('app1', '0003_accinvmast_accledgers_accmaster_cashandbankaccmaster'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='shoplocation',
            index=models.Index(fields=['firm', 'client_id'], name='idx_firm_client'),
        ),
        migrations.AddIndex(
            model_name='shoplocation',
            index=models.Index(fields=['created_at'], name='idx_created_at'),
        ),
    ]
