# Generated by Django 5.0.2 on 2025-08-30 05:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PunchIn', '0002_shoplocation_idx_firm_client_and_more'),
        ('app1', '0003_accinvmast_accledgers_accmaster_cashandbankaccmaster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoplocation',
            name='firm',
            field=models.ForeignKey(db_column='firm_code', db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='shop_locations', to='app1.accmaster'),
        ),
    ]
