# Generated by Django 5.0.2 on 2025-09-18 05:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PunchIn', '0003_alter_shoplocation_firm'),
        ('app1', '0003_accinvmast_accledgers_accmaster_cashandbankaccmaster'),
    ]

    operations = [
        migrations.CreateModel(
            name='PunchIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('client_id', models.CharField(db_index=True, max_length=64)),
                ('punchin_time', models.DateTimeField(auto_now_add=True)),
                ('punchout_time', models.DateTimeField(blank=True, null=True)),
                ('photo_url', models.URLField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'punchin',
                'ordering': ['-punchin_time'],
            },
        ),
        migrations.RenameIndex(
            model_name='shoplocation',
            new_name='idx_shop_firm_client',
            old_name='idx_firm_client',
        ),
        migrations.RenameIndex(
            model_name='shoplocation',
            new_name='idx_shop_created_at',
            old_name='idx_created_at',
        ),
        migrations.AddField(
            model_name='punchin',
            name='firm',
            field=models.ForeignKey(db_column='firm_code', db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='punchins', to='app1.accmaster'),
        ),
        migrations.AddIndex(
            model_name='punchin',
            index=models.Index(fields=['firm', 'client_id'], name='idx_punchin_firm_client'),
        ),
        migrations.AddIndex(
            model_name='punchin',
            index=models.Index(fields=['punchin_time'], name='idx_punchin_time'),
        ),
    ]
