# Generated by Django 5.0.2 on 2025-09-19 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PunchIn', '0004_punchin_rename_idx_firm_client_idx_shop_firm_client_and_more'),
        ('app1', '0003_accinvmast_accledgers_accmaster_cashandbankaccmaster'),
    ]

    operations = [
        migrations.AddField(
            model_name='punchin',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='punchin',
            name='created_by',
            field=models.CharField(default=0, max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='punchin',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='punchin',
            name='photo_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddIndex(
            model_name='punchin',
            index=models.Index(fields=['client_id', 'created_by'], name='idx_punchin_client_user'),
        ),
    ]
