# Generated by Django 5.0.2 on 2025-10-13 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PunchIn', '0005_punchin_address_punchin_created_by_punchin_notes_and_more'),
        ('app1', '0003_accinvmast_accledgers_accmaster_cashandbankaccmaster'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAreas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_code', models.CharField(db_column='area_code', max_length=64)),
                ('user', models.ForeignKey(db_column='user_id', db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='Areas', to='app1.accuser')),
            ],
            options={
                'db_table': 'user_areas',
            },
        ),
        migrations.AddConstraint(
            model_name='userareas',
            constraint=models.UniqueConstraint(fields=('user', 'area_code'), name='uniq_user_area'),
        ),
    ]
