# Generated by Django 5.0.2 on 2025-10-17 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PunchIn', '0006_userareas_userareas_uniq_user_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='userareas',
            name='client_id',
            field=models.CharField(db_index=True, default='SYSMAC', max_length=64),
            preserve_default=False,
        ),
    ]
