# Generated by Django 5.0.2 on 2026-03-23 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TenderCash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=50)),
                ('mslno', models.BigIntegerField()),
                ('tender_code', models.CharField(max_length=7)),
                ('amount', models.DecimalField(decimal_places=3, max_digits=12)),
                ('currency_code', models.CharField(max_length=10)),
                ('currency_name', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'tendercash',
            },
        ),
    ]
