# Generated by Django 5.0.2 on 2025-07-23 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccUser',
            fields=[
                ('id', models.CharField(db_column='id', max_length=64, primary_key=True, serialize=False)),
                ('password', models.CharField(db_column='pass', max_length=128)),
                ('role', models.CharField(blank=True, max_length=32, null=True)),
                ('accountcode', models.CharField(blank=True, max_length=64, null=True)),
            ],
            options={
                'db_table': 'acc_users',
                'managed': False,
            },
        ),
    ]
