# Generated by Django 5.0.2 on 2025-07-25 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Misel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('firm_name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('phones', models.CharField(max_length=50)),
                ('mobile', models.CharField(blank=True, max_length=50, null=True)),
                ('address1', models.CharField(max_length=255)),
                ('address2', models.CharField(max_length=255)),
                ('address3', models.CharField(max_length=255)),
                ('pagers', models.CharField(max_length=255)),
                ('tinno', models.CharField(max_length=50)),
                ('client_id', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'misel',
                'managed': False,
            },
        ),
    ]
