# Generated by Django 5.0.2 on 2025-08-12 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_misel'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccInvmast',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('modeofpayment', models.CharField(blank=True, max_length=10, null=True)),
                ('customerid', models.CharField(blank=True, max_length=30, null=True)),
                ('invdate', models.DateField(blank=True, null=True)),
                ('nettotal', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('paid', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('bill_ref', models.CharField(blank=True, max_length=100, null=True)),
                ('client_id', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'acc_invmast',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AccLedgers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=30)),
                ('particulars', models.CharField(blank=True, max_length=500, null=True)),
                ('debit', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('credit', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('entry_mode', models.CharField(blank=True, max_length=20, null=True)),
                ('entry_date', models.DateField(blank=True, null=True)),
                ('voucher_no', models.IntegerField(blank=True, null=True)),
                ('narration', models.TextField(blank=True, null=True)),
                ('client_id', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'acc_ledgers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AccMaster',
            fields=[
                ('code', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('opening_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('debit', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('credit', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('place', models.CharField(blank=True, max_length=100, null=True)),
                ('phone2', models.CharField(blank=True, max_length=60, null=True)),
                ('openingdepartment', models.CharField(blank=True, max_length=100, null=True)),
                ('client_id', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'acc_master',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CashAndBankAccMaster',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=250)),
                ('super_code', models.CharField(blank=True, max_length=5, null=True)),
                ('opening_balance', models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True)),
                ('opening_date', models.DateField(blank=True, null=True)),
                ('debit', models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True)),
                ('credit', models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True)),
                ('client_id', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'cashandbankaccmaster',
                'managed': False,
            },
        ),
    ]
