# Generated by Django 5.0.2 on 2026-03-23 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PDC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=50)),
                ('colndate', models.DateField()),
                ('party', models.CharField(blank=True, max_length=30, null=True)),
                ('amount', models.DecimalField(decimal_places=3, max_digits=10, null=True)),
                ('chequedate', models.DateField(blank=True, null=True)),
                ('chequeno', models.CharField(blank=True, max_length=20, null=True)),
                ('colnstatus', models.CharField(blank=True, max_length=1, null=True)),
                ('status', models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                'db_table': 'pdc',
            },
        ),
    ]
